DROP SCHEMA mkyongdb;

CREATE SCHEMA mkyongdb;

CREATE TABLE mkyongdb.stock (
  STOCK_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
  STOCK_CODE VARCHAR(10) NOT NULL,
  STOCK_NAME VARCHAR(20) NOT NULL
);

INSERT INTO mkyongdb.stock VALUES(1, 'A', 'SOMETHING');
INSERT INTO mkyongdb.stock VALUES(2, 'B', 'SOMETHING ELSE');

CREATE TABLE mkyongdb.category (
  CATEGORY_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL
);

INSERT INTO mkyongdb.category VALUES(10, 'CAT10', 'CATEGORY twenty');
INSERT INTO mkyongdb.category VALUES(20, 'CAT20', 'zorglub');

CREATE TABLE mkyongdb.role (
  ROLE_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
  ROLE_NAME VARCHAR(20) NOT NULL
);

INSERT INTO mkyongdb.role VALUES(1,	'role1');
INSERT INTO mkyongdb.role VALUES(2, 'role2');
INSERT INTO mkyongdb.role VALUES(3, 'role3');

CREATE TABLE  mkyongdb.stock_category_role (
  STOCK_ID INT(10) NOT NULL,
  CATEGORY_ID INT(10) NOT NULL,
  ROLE_ID INT(10) NOT NULL,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10),
  PRIMARY KEY (STOCK_ID,CATEGORY_ID,ROLE_ID),
  CONSTRAINT FK_STOCK_ID FOREIGN KEY (STOCK_ID) 
             REFERENCES STOCK (STOCK_ID),
  CONSTRAINT FK_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) 
             REFERENCES CATEGORY (CATEGORY_ID),
  CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) 
             REFERENCES role (ROLE_ID)
);

INSERT INTO mkyongdb.stock_category_role VALUES(1, 10, 1,null,null);
INSERT INTO mkyongdb.stock_category_role VALUES(1, 10, 2,null,null);
INSERT INTO mkyongdb.stock_category_role VALUES(1, 20, 1,null,null);
